# Generated by Django 3.1.7 on 2021-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('photo', models.ImageField(upload_to='upload/images/room')),
                ('price', models.CharField(max_length=4)),
                ('price_level', models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$'), ('5', '$$$$$')], max_length=1)),
            ],
            options={
                'ordering': ['price_level'],
            },
        ),
    ]
